export const questions: {name: string, setName: string, imageUrl: string, question: string, answer: string}[] = [
  /* ========== ILIAD SET (10) ========== */
  {
    name: "Achilles’ Shield",
    setName: "Iliad",
    imageUrl: "/achilles_shield.png",
    question: "Which god forged Achilles’ shield for him?",
    answer: "hephaestus",
  },
  {
    name: "Briseis’ Brooch",
    setName: "Iliad",
    imageUrl: "/briseis_brooch.png",
    question: "Which woman’s capture causes a quarrel between Achilles and Agamemnon?",
    answer: "briseis",
  },
  {
    name: "Myrmidon Banner",
    setName: "Iliad",
    imageUrl: "/myrmidon_banner.jpg",
    question: "What name is given to Achilles’ elite warriors led by him?",
    answer: "myrmidons",
  },
  {
    name: "Palladium Idol",
    setName: "Iliad",
    imageUrl: "/palladium.jpg",
    question: "Which sacred image's removal was said to doom Troy?",
    answer: "palladium",
  },
  {
    name: "Chryseis’ Pendant",
    setName: "Iliad",
    imageUrl: "/pendant.jpg",
    question: "Which priest’s daughter, taken from the Greeks, caused Apollo’s plague?",
    answer: "chryseis",
  },
  {
    name: "Ajax’s Great Shield",
    setName: "Iliad",
    imageUrl: "/ajax_shield.jpg",
    question: "Which hero is famed for his huge defensive shield and strength?",
    answer: "ajax",
  },
  {
    name: "Patroclus’ Sandal",
    setName: "Iliad",
    imageUrl: "/sandal.jpg",
    question: "Whose death wearing Achilles’ armour spurs Achilles back into battle?",
    answer: "patroclus",
  },
  {
    name: "Scamander Stone",
    setName: "Iliad",
    imageUrl: "/stone.jpeg",
    question: "By what alternate name is the river Scamander known in the epics?",
    answer: "xanthus",
  },
  {
    name: "Doloneia Cloak",
    setName: "Iliad",
    imageUrl: "/cloak.jpg",
    question: "Which spy’s night mission and capture is narrated in the 'Doloneia'?",
    answer: "dolon",
  },
  {
    name: "Priam’s Shroud",
    setName: "Iliad",
    imageUrl: "/shroud.jpg",
    question: "Which Trojan king begged Achilles for the ransom of Hector’s body?",
    answer: "priam",
  },
  /* ========== GODS SET (10) ========== */
  {
    name: "Nike’s Wreath",
    setName: "Gods",
    imageUrl: "/wreath.png",
    question: "Which winged goddess personifies victory?",
    answer: "nike",
  },
  {
    name: "Hecate’s Torch",
    setName: "Gods",
    imageUrl: "/torch.jpg",
    question: "Which goddess, associated with crossroads and magic, carries torches?",
    answer: "hecate",
  },
  {
    name: "Pan’s Pipes",
    setName: "Gods",
    imageUrl: "/panpipes.jpg",
    question: "Which rustic god is famed for his syrinx (panpipes)?",
    answer: "pan",
  },
  {
    name: "Hebe’s Cup",
    setName: "Gods",
    imageUrl: "/cup.jpg",
    question: "Which goddess served ambrosia to the gods as cupbearer before Ganymede?",
    answer: "hebe",
  },
  {
    name: "Harmonia’s Necklace",
    setName: "Gods",
    imageUrl: "/necklace.png",
    question: "Which object, given at a wedding, brought discord and misfortune in myth?",
    answer: "necklace",
  },
  {
    name: "Hestia’s Hearth",
    setName: "Gods",
    imageUrl: "/hearth.jpg",
    question: "Which virgin goddess presides over the hearth and domestic flame?",
    answer: "hestia",
  },
  {
    name: "Eris’ Apple",
    setName: "Gods",
    imageUrl: "/golden_apple.jpeg",
    question: "Which goddess caused the judgement leading to the Trojan War by tossing a golden apple?",
    answer: "eris",
  },
  {
    name: "Prometheus’ Chain",
    setName: "Gods",
    imageUrl: "/chain.png",
    question: "Which Titan stole fire for humans and was punished chained to a rock?",
    answer: "prometheus",
  },
  {
    name: "Ganymede's Eagle",
    setName: "Gods",
    imageUrl: "/eagle.png",
    question: "Which beautiful youth was taken to Olympus to be cupbearer to the gods?",
    answer: "ganymede",
  },
  {
    name: "Ananke’s Rope",
    setName: "Gods",
    imageUrl: "/rope.png",
    question: "Which personification represents inevitability and necessity in Greek thought?",
    answer: "ananke",
  }
]
